---
markdown: kramdown
kramdown:
  parse_block_html: true

sass:
  syntax: scss
  style: compressed  # nested|expanded|compact|compressed
  deploy_style: compressed # nested|expanded|compact|compressed
